ALTER TABLE shodhan_instructors
  ADD COLUMN IF NOT EXISTS gender VARCHAR(1) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS age INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS experience_years INTEGER DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS telegram VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS vk VARCHAR(100) DEFAULT NULL;
