ALTER TABLE shodhan_instructors ADD COLUMN IF NOT EXISTS cities TEXT[] NOT NULL DEFAULT '{}';

UPDATE shodhan_instructors SET cities = CASE id
  WHEN 2 THEN ARRAY['Мостовской']
  WHEN 10 THEN ARRAY['Мостовской']
  WHEN 11 THEN ARRAY['Белгород']
  WHEN 12 THEN ARRAY['Омск']
  WHEN 13 THEN ARRAY['Москва']
  WHEN 14 THEN ARRAY['Чебоксары']
  WHEN 15 THEN ARRAY['Нижний Новгород']
  WHEN 16 THEN ARRAY['Санкт-Петербург']
  WHEN 17 THEN ARRAY['Корсаков','Южно-Сахалинск']
  WHEN 18 THEN ARRAY['Санкт-Петербург']
  WHEN 19 THEN ARRAY['Москва']
  WHEN 20 THEN ARRAY['Владивосток']
  WHEN 21 THEN ARRAY['Тольятти']
  WHEN 22 THEN ARRAY['Воронеж','Мичуринск']
  WHEN 23 THEN ARRAY['Стерлитамак']
  WHEN 24 THEN ARRAY['Ростов-на-Дону','Таганрог']
  WHEN 25 THEN ARRAY['Петропавловск-Камчатский']
  WHEN 26 THEN ARRAY['Воронеж']
  WHEN 27 THEN ARRAY['Тюмень']
  WHEN 28 THEN ARRAY['Калининград']
  WHEN 29 THEN ARRAY['Калининград']
  WHEN 30 THEN ARRAY['Москва']
  WHEN 31 THEN ARRAY['Санкт-Петербург']
  WHEN 32 THEN ARRAY['Октябрьский','Марково','Покров']
  WHEN 33 THEN ARRAY['Бердянск']
  WHEN 34 THEN ARRAY['Чебоксары']
  WHEN 35 THEN ARRAY['Екатеринбург']
  WHEN 36 THEN ARRAY['Санкт-Петербург']
  WHEN 37 THEN ARRAY['Краснодар','Севастополь']
  WHEN 38 THEN ARRAY['Санкт-Петербург']
  WHEN 39 THEN ARRAY['Новосибирск']
  WHEN 40 THEN ARRAY['Воронеж','Москва','Нижний Новгород']
  WHEN 41 THEN ARRAY['Ростов-на-Дону']
  WHEN 42 THEN ARRAY['Барнаул']
  WHEN 43 THEN ARRAY['Новосибирск']
  WHEN 44 THEN ARRAY['Клин']
  WHEN 45 THEN ARRAY['Казань']
  WHEN 46 THEN ARRAY['Сочи']
  WHEN 47 THEN ARRAY['Москва']
  WHEN 48 THEN ARRAY['Краснодар']
  WHEN 49 THEN ARRAY['Кемерово']
  WHEN 50 THEN ARRAY['Батуми']
  WHEN 51 THEN ARRAY['Красноярск']
  WHEN 52 THEN ARRAY['Сочи']
  WHEN 53 THEN ARRAY['Москва']
  WHEN 54 THEN ARRAY['Сочи']
END WHERE id IN (2,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54);

UPDATE shodhan_instructors SET cities = ARRAY[city] WHERE cities = '{}' AND city IS NOT NULL AND city != '';
